/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WaldieAgentHumanInputMode = 'ALWAYS' | 'NEVER' | 'TERMINATE';
export type WaldieAgentCodeExecutionConfig = WaldieAgentCodeExecutionConfigDict | false;
export type WaldieAgentTypeTerminationTypeOption = 'none' | 'keyword' | 'method';
export type WaldieAgentTerminationCriterionOption = 'found' | 'ending' | 'exact';
export type WaldieGroupManagerSpeakerSelectionMethodOption =
  | 'auto'
  | 'manual'
  | 'random'
  | 'round_robin'
  | 'custom';
export type SpeakerSelectionMode = 'repeat' | 'transition';
export type SpeakerTransitionsType = 'allowed' | 'disallowed';
export type WaldieModelAPIType =
  | 'openai'
  | 'azure'
  | 'google'
  | 'anthropic'
  | 'mistral'
  | 'grog'
  | 'together'
  | 'other'
  | null;
export type WaldieMessageType = 'string' | 'method' | 'none' | 'last_carryover' | 'rag_message_generator';
export type WaldieEdgeLlmSummaryMethod = 'reflection_with_llm' | 'last_msg' | null;

/**
 * Waldie Schema.
 */
export interface HttpsGithubComWaldiezJsTreeV001SchemaJson {
  type: 'flow';
  id?: string;
  name: string;
  description: string;
  tags: string[];
  requirements: string[];
  data: {
    nodes: {
      [k: string]: unknown;
    }[];
    edges: {
      [k: string]: unknown;
    }[];
    viewport?: {
      [k: string]: unknown;
    };
    agents: {
      users: WaldieUserProxy[];
      assistants: WaldieAssistant[];
      managers: WaldieGroupManager[];
    };
    models: WaldieModel[];
    skills: WaldieSkill[];
    chats: WaldieChat[];
  };
}
/**
 * Waldie User Proxy Agent.
 */
export interface WaldieUserProxy {
  id?: string;
  type: 'agent';
  agentType: 'user';
  name: string;
  description: string;
  tags: string[];
  requirements: string[];
  data: {
    systemMessage: string | null;
    humanInputMode: WaldieAgentHumanInputMode;
    maxTokens: number | null;
    codeExecutionConfig: WaldieAgentCodeExecutionConfig;
    agentDefaultAutoReply: string | null;
    maxConsecutiveAutoReply: number | null;
    termination: WaldieAgentTerminationMessageCheck;
    teachability: WaldieAgentTeachability;
    modelIds: string[];
    skills: WaldieAgentLinkedSkill[];
    requirements: string[];
    nestedChats: WaldieAgentNestedChat[];
  };
}
export interface WaldieAgentCodeExecutionConfigDict {
  workDir?: string;
  useDocker?: string | string[] | boolean;
  timeout?: number;
  lastNMessages?: number | 'auto';
  functions?: string[];
}
export interface WaldieAgentTerminationMessageCheck {
  type: WaldieAgentTypeTerminationTypeOption;
  keywords: string[];
  criterion: WaldieAgentTerminationCriterionOption | null;
  methodContent: string | null;
}
export interface WaldieAgentTeachability {
  enabled: boolean;
  verbosity: 0 | 1 | 2 | 3;
  resetDb: boolean;
  recallThreshold: number;
  maxMumRetrievals: number;
}
export interface WaldieAgentLinkedSkill {
  id: string;
  executorId: string;
}
export interface WaldieAgentNestedChat {
  triggeredBy: {
    id: string;
    isReply: boolean;
  }[];
  messages: {
    id: string;
    isReply: boolean;
  }[];
}
/**
 * Waldie Assistant Agent.
 */
export interface WaldieAssistant {
  id?: string;
  type: 'agent';
  agentType: 'assistant';
  name: string;
  description: string;
  tags: string[];
  requirements: string[];
  data: {
    systemMessage: string | null;
    humanInputMode: WaldieAgentHumanInputMode;
    maxTokens: number | null;
    codeExecutionConfig: WaldieAgentCodeExecutionConfig;
    agentDefaultAutoReply: string | null;
    maxConsecutiveAutoReply: number | null;
    termination: WaldieAgentTerminationMessageCheck;
    teachability: WaldieAgentTeachability;
    modelIds: string[];
    skills: WaldieAgentLinkedSkill[];
    requirements: string[];
    nestedChats: WaldieAgentNestedChat[];
  };
}
/**
 * Waldie Group Chat Manager Agent.
 */
export interface WaldieGroupManager {
  id?: string;
  type: 'agent';
  agentType: 'manager';
  name: string;
  description: string;
  tags: string[];
  requirements: string[];
  data: {
    systemMessage: string | null;
    humanInputMode: WaldieAgentHumanInputMode;
    maxTokens: number | null;
    codeExecutionConfig: WaldieAgentCodeExecutionConfig;
    agentDefaultAutoReply: string | null;
    maxConsecutiveAutoReply: number | null;
    termination: WaldieAgentTerminationMessageCheck;
    teachability: WaldieAgentTeachability;
    modelIds: string[];
    skills: WaldieAgentLinkedSkill[];
    requirements: string[];
    maxRound: number | null;
    adminName: string | null;
    speakers: WaldieWaldieGroupManagerSpeakers;
    enableClearHistory?: boolean;
    sendIntroductions?: boolean;
  };
}
export interface WaldieWaldieGroupManagerSpeakers {
  selectionMethod: WaldieGroupManagerSpeakerSelectionMethodOption;
  selectionCustomMethod: string;
  maxRetriesForSelecting: number | null;
  selectionMode: SpeakerSelectionMode;
  allowRepeat: boolean | string[];
  allowedOrDisallowedTransitions: {
    [k: string]: string[];
  };
  transitionsType: SpeakerTransitionsType;
}
/**
 * Waldie Model.
 */
export interface WaldieModel {
  id?: string;
  type: 'model';
  name: string;
  description: string;
  tags: string[];
  requirements: string[];
  data: {
    baseUrl: string | null;
    apiKey: string | null;
    apiType: WaldieModelAPIType;
    apiVersion: string | null;
    temperature: number | null;
    topP: number | null;
    maxTokens: number | null;
    defaultHeaders: {
      [k: string]: string;
    };
    price: WaldieModelPrice | null;
    requirements: string[];
  };
}
export interface WaldieModelPrice {
  promptPricePer1k: number | null;
  completionTokenPricePer1k: number | null;
}
/**
 * Waldie Skill.
 */
export interface WaldieSkill {
  id?: string;
  type: 'skill';
  name: string;
  description: string;
  tags: string[];
  requirements: string[];
  data: {
    content: string;
    secrets: {
      [k: string]: string;
    };
    requirements: string[];
  };
}
/**
 * Waldie Chat.
 */
export interface WaldieChat {
  id?: string;
  data: {
    name: string;
    source: string;
    target: string;
    description: string;
    position: number;
    clearHistory: boolean | null;
    message: WaldieMessage;
    nestedChat: {
      message: WaldieMessage | null;
      reply: WaldieMessage | null;
    };
    maxTurns: number | null;
  };
}
/**
 * Waldie Message.
 *
 * A generic message with a type and content.
 *
 * If the type is not 'none', the content is a string. If the type is 'method', the content is the code of a method.
 */
export interface WaldieMessage {
  type: WaldieMessageType;
  content: string | null;
  context: { [key: string]: any };
}
