---
name: Lint, test, and docs
    
# yamllint disable rule:truthy
on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint

  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v2
        - name: Install dependencies
          run: bun install
        - name: Prepare Playwright
          run: npx playwright install
        - name: Run tests
          run: bun run test:all
        - name: Report to Coveralls
          uses: coverallsapp/github-action@v2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: coverage/lcov.info

  docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build docs
        run: bun run docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out/docs'

  deploy-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

