---
name: Release

# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
