---
name: Release

# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
  id-token: write

jobs: 
  release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Read changelog
          id: changelog
          run: |
            echo "changelog=$(bun changelog)" >> $GITHUB_ENV
            echo "changelog<<EOF" >> $GITHUB_OUTPUT
            bun changelog >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
        - name: Setup bun
          if: steps.changelog.outputs.changelog != ''
          uses: oven-sh/setup-bun@v2
        - name: Install dependencies
          if: steps.changelog.outputs.changelog != ''
          run: bun install
        - name: Build
          if: steps.changelog.outputs.changelog != ''
          run: bun build:lib
        - name: Release
          id: create_release
          if: steps.changelog.outputs.changelog != ''
          uses: softprops/action-gh-release@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref_name }}
            name: Release ${{ github.ref_name }}
            # body: the changelog
            body: ${{ steps.changelog.outputs.changelog }}
            draft: false
            prerelease: false
        - name: Publish to NPM
          if: steps.create_release.outputs.id
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: bun publish
