---
name: Release

# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun build:lib
  release:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Release
          uses: go-semantic-release/action@v1
          id: semrel
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Publish to NPM
          if: steps.semrel.outputs.version != ''
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: bun publish
