---
name: Release

# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
  id-token: write

jobs: 
  release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup bun
          uses: oven-sh/setup-bun@v2
        - name: Install dependencies
          run: bun install
        - name: Build
          run: bun build:lib
        - name: Read changelog
          id: changelog
          run: echo "::set-output name=changelog::$(bun changelog)"
        - name: Release
          id: create_release
          if: steps.changelog.outputs.changelog != ''
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            # body: the changelog
            body: ${{ steps.changelog.outputs.changelog }}
            draft: false
            prerelease: false
        - name: Publish to NPM
          if: steps.create_release.outputs.id
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: bun publish
